# Generated by Django 6.0.3 on 2026-04-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_employee_attendance_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='food_deduction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('half', 'Half Day')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='salary',
            name='present_days',
            field=models.FloatField(default=0),
        ),
    ]
