# Generated by Django 6.0.3 on 2026-04-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_employee_food_deduction_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('paid_leave', 'Paid Leave'), ('half', 'Half Day')], default='present', max_length=20),
        ),
    ]
