# Generated by Django 6.0.3 on 2026-04-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_attendance_overtime_hours_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='food_rate',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('paid_leave', 'Paid Leave'), ('half', 'Half Day'), ('weekly_off', 'Weekly Off')], default='present', max_length=20),
        ),
    ]
