# Generated by Django 6.0.3 on 2026-04-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_employee_food_rate_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
