# Generated by Django 6.0.3 on 2026-04-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_employee_overtime_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
